### ISSUE TITLE
Umístění release

### ISSUE THREAD

**Issue by Bystroushaak** [NLCR/CZIDLO#127]
Ahoj.

V manuálu se píše: *This archive should contain these files:*

Jen nevím, kde ten *archive* sebrat. Dřív byl asi na google code, ale teď ho nikde nemůžu najít. Je někde umístěný?

**Comment by rzeh4n** [comment]
Tady: https://github.com/NLCR/CZIDLO/releases
Jsou tam jen novější releasy.
Jak už jsem psal, README.TXT vznikl před migrací na github. Je v zipu každého releasu a je určen jako návod na instalaci.

**Comment by Bystroushaak** [comment]
Díky, jsem slepej.
