### ISSUE TITLE
CZIDLO nejde buildnout v mavenu ani s -DskipTests

### ISSUE THREAD

**Issue by westfood** [NLCR/CZIDLO#149]
Zkoušel jsem `mvn package`. Ale nepodařilo se mi vytvořit WAR kontejnery.

Došlo k nějakým změnám v maven repo u groupId např. `postgresql > org.postgresql`, `xom > com.io7m.xom`. V maven repo je místo jdbc-stdext-2.0.jar jen jdbc-stdext-2.0-sources.jar, lokálně jsem si všiml jdbc-stdext-2.0.jar, tak jsem ho zkusil přidat:
`
<scope>system</scope> 
<systemPath>${basedir}/jdbc-stdext-2.0.jar</systemPath>
`
ale nakonec to vymřelo na nepřítomnost jta-1.0.1B.jar a víc jsem se v tom nevrtal.

**Comment by westfood** [comment]
Přemýšlím, že bych časem připravil mirror pro potřebné artefakty, ale ještě musím prostudovat jak to funguje: https://www.jfrog.com/open-source/#os-bin, https://bintray.com. Ideálně něco co už funguje.

**Comment by rzeh4n** [comment]
Chtělo by to podrobnější popis chyby. To, že v maven repozitářích se groupId občas mění z novou verzí artefaktu, je docela častý jev.

**Comment by westfood** [comment]
Tohle je pro ten chybějící jta-1.0.1B.jar - nenašel jsem ho v maven repo. Myslel jsem že ty změny vychytám a pošlu push request, ale nebyl jsem si jist, kolik změn se ještě ukáže.
> Downloading: https://repo.maven.apache.org/maven2/javax/transaction/jta/1.0.1B/jta-1.0.1B.jar
[INFO] CZIDLO - processManager ............................ FAILURE [  1.475 s]
Failed to execute goal on project processManager: Could not resolve dependencies for project cz.nkp.urnnbn:processManager:jar:4.3: Could not find artifact javax.transaction:jta:jar:1.0.1B in central (https://repo.maven.apache.org/maven2), try downloading from http://java.sun.com/products/jta -> [Help 1]

**Comment by rzeh4n** [comment]
Nahrál jsem v 42e6885e825580e0a0ba555f411ed3f29c838743 chybějící jar pro jta. Měl jsem ten artefakt nainstalovaný lokálně už nějakou dobu, tak mi to nedošlo. Pokud se ještě něco objeví, zase doplním takhle.

**Comment by westfood** [comment]
Ještě jedna chyba, kde jsem nedohledal verzi závislosti..

``[INFO] CZIDLO - web (client) .............................. FAILURE [  1.273 s]    
Failed to execute goal on project web_client: Could not resolve dependencies for project cz.nkp.urnnbn:web_client:war:4.3: The following artifacts could not be resolved: com.smartgwt:smartgwt:jar:5.1p, com.googlecode.gwtquery.bundles:gquery-dnd-bundle:jar:1.0.6: Could not find artifact com.smartgwt:smartgwt:jar:5.1p in central (https://repo.maven.apache.org/maven2)``

Hele, podle ofiko dokumentace bych si měl nahrál 3d party jar do svého lokálního repo. Mně se ale zdá rozumnější používat ten tenhle přístup v pom.xml:  ``<scope>system</scope> <systemPath>${basedir}/jdbc-stdext-2.0.jar</systemPath> `` -- myslíš že je to cajk?

**Comment by rzeh4n** [comment]
No asi jo, protože některé ty věci nejsou ve veřejných maven repozitářich z licenčních/právních důvodů a člověk si to musí stahovat ručně. Takže dost možná nebude ok mít to ve vlastní (veřejné) repozitory pro NKP.
5613696e079b62ed81fb64180e0b96036f4feec9
https://github.com/NLCR/CZIDLO/blob/master/web/web_client/pom.xml#L54

**Comment by rzeh4n** [comment]
Pokud jde od ten scope system, tak tohle stejně nefunguje pro ty GWT moduly. Třeba
```
<dependency>
            <groupId>com.googlecode.gwtquery.bundles</groupId>
            <artifactId>gquery-dnd-bundle</artifactId>
            <version>1.0.6</version>
            <scope>system</scope>
            <systemPath>{basedir}/missing_maven_artifacts/gquery-dnd-bundle-1.0.6.jar</systemPath>
        </dependency>
```
Skončí s 

> [ERROR] 'dependencies.dependency.systemPath' for com.smartgwt:smartgwt:jar must specify an absolute path but is {basedir}/missing_maven_artifacts/smartgwt-5.1p.jar @ cz.nkp.urnnbn:web_client:[unknown-version], /home/martin/git/CZIDLO/web/web_client/pom.xml, line 62, column 25

Takže to nechám tak - nutná instalace do lokálního repa, akorát build bude pořádně zdokumentovaný na https://github.com/NLCR/CZIDLO/wiki/Build a všechny chybějící knihovny budou v adresáři missing_maven_artifacts
