### ISSUE TITLE
Přidat dokumentaci pro build s testem

### ISSUE THREAD

**Issue by westfood** [NLCR/CZIDLO#150]
Zkoušel jsem `mvn package` ale testy zdá se zkouší databázi: 

> Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

Asi bych měl někde nastavit parametry pro dbs?

**Comment by rzeh4n** [comment]
Pokud jde o modul api, tak tam se predpoklada existence "testovaci" verze api právě builděné verze. Vím, trochu hlava 22, ale je to určené pro vývoj. Stačí testy vypnout přes -Dmaven.test.skip=true
Takže třeba takto:
`mvn clean install package -Dmaven.test.skip=true`

Tady se o tom zmiňuju:
https://github.com/NLCR/CZIDLO/blob/master/api/pom.xml

Aby ty testy prošly, je potřeba, aby byl nasazený modul api (který v poslední verzi obsahuje API verze 3 i 4) nad realnou databází. Data jako uživatelské účty, registrátoři apod., které je potřeba kvůli testům vytvořit, jsou definována tady:
https://github.com/NLCR/CZIDLO/blob/master/api/src/test/java/cz/nkp/urnnbn/api/v3/ApiV3Tests.java
https://github.com/NLCR/CZIDLO/blob/master/api/src/test/java/cz/nkp/urnnbn/api/v4/ApiV4Tests.java

**Comment by westfood** [comment]
Díky, časem vyzkouším a zkusím přidat košér postup i s testama na wiki.

**Comment by rzeh4n** [comment]
Testy pro moduly persistence a api byly vypnuty na úrovni pom.xml jednotlivých modulů. Jsou to spíš integrační testy, takže tam úplně nepatří při standardním buildu, pokud nemá člověk nastaveno to testovací prostředí. Raději takto, než vypínat úplně všechno, včetně unit testů v dalších modulech.
