### ISSUE TITLE
tlacitko pro planovani procesu by melo byt disabled, dokud nejsou vyplnene povinne parametry

### ISSUE THREAD

**Issue by rzeh4n** [NLCR/CZIDLO#165]
Napr. pro OAI Adapter to je OAI base URL a metadatovy format. Bez techto udaju nema smysl se pokouset spoustet proces, takze by to webove rozhrani nemelo ani umoznovat.

**Comment by ZdenekVasek** [comment]
Ano, to je praktické. Zvláště, pokud se správa rozšíří i mimo adminy NK, což lze očekávat.

**Comment by rzeh4n** [comment]
Vyřešeno, ale trochu jinak. To tlačítko není disabled, jen nereaguje, dokud není formulář v dialogu řádně vyplněný. Stejně tak se chovájí dialogy i pro ostatní procesy.
