### ISSUE TITLE
řazení registrátorů ve webovém rozhraní

### ISSUE THREAD

**Issue by rzeh4n** [NLCR/CZIDLO#166]
Registrátoři by měli být nějak seřazeni, buď podle názvů, nebo podle kódů, záleží na kontextu. Jinak se v tom ve větším počtu nedá vyznat.

**Comment by rzeh4n** [comment]
Aha, on tam je atribut "order" jakože pořadí v seznamu registrátorů, protože šlo ty registrátory v tabulce přeuspořádávat po přihlášení pro adminy. 
To je UX totální nesmysl, odstraním to.

**Comment by ZdenekVasek** [comment]
V tom případě nejlépe podle kódů.

**Comment by rzeh4n** [comment]
Zatím jsem to změnil tak, že na https://resolver.nkp.cz/web/#tab3 se bude řadit podle názvů registrátorů/archivátorů, protože na tomhle místě ty kódy viditelné nejsou. Ale stejně jsem měl v plánu tam kódy taky zobrazit, celkem tedy názvev, kód a tlačítka (podrobonosti, upravit), viz #169. A potom tedy bych tam nechal možnost přepnout mezi seřazení podle názvu, nebo kódu.
Na místech, kde jsou jenom kódy (např. seznam registrátorů, ke kterým má uživatel práva), tak se bude řadit jen podle kódů. To ještě doplním.

**Comment by rzeh4n** [comment]
Opraveno, ještě se to řadí trochu podivně, pokud jsou v názvech na začátku bílé znaky, viz #164
