### ISSUE TITLE
sjednotit terminologi a eng lokalizace - archiver vs archivar

### ISSUE THREAD

**Issue by rzeh4n** [NLCR/CZIDLO#167]
Asi by se mělo zachovat archivar, podobně jako registrar. Jednak ve zdrojových kódech, v anglické lokalizaci, ale i v názvech databázových tabulek, indexů apod.

**Comment by ZdenekVasek** [comment]
Se sjednocením souhlasím. Doporučuji na archiver.

**Comment by rzeh4n** [comment]
Aha, tak všude je "archiver" a není co opravovat. Moje chyba.
