### ISSUE TITLE
Chyba pri vyhledavani

### ISSUE THREAD

**Issue by innaskoupa** [NLCR/CZIDLO#203]
Kdyz zadam v vyhledavani cokoliv se znakem"\", tak hlasi 

> chyba na serveru: Error from server at http://localhost:8983/solr: org.apache.solr.search.SyntaxError: Cannot parse '\': Lexical error at line 1, column 2.  Encountered: <EOF> after : ""

**Comment by rzeh4n** [comment]
Ve verzích 4.6 a 4.6.1 se mi nepodařilo replikovat.
