### ISSUE TITLE
Testovací instance resolveru je nedostupná

### ISSUE THREAD

**Issue by ZdenkaSera** [NLCR/CZIDLO#254]
V pátek 13.9. jsme zaregistrovali nedostupnost testovací instance resolveru, dnes potíže přetrvávají.

**Comment by rzeh4n** [comment]
@ZdenkaSera Už by to zase mělo fungovat.

**Comment by ZdenkaSera** [comment]
@rzeh4n Ano, funguje - děkujeme, issue zavírám.
